export enum Permission {
  // Kullanıcı Yönetimi
  USER_LIST = 'USER_LIST',
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_SOFT_DELETE = 'USER_SOFT_DELETE',
  USER_ASSIGN_ROLE = 'USER_ASSIGN_ROLE',

  // Rol & Yetki Yönetimi
  ROLE_LIST = 'ROLE_LIST',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_MANAGE_PERMISSIONS = 'ROLE_MANAGE_PERMISSIONS',

  // Üye Yönetimi
  MEMBER_LIST = 'MEMBER_LIST',
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE_APPLICATION = 'MEMBER_CREATE_APPLICATION',
  MEMBER_APPROVE = 'MEMBER_APPROVE',
  MEMBER_REJECT = 'MEMBER_REJECT',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_STATUS_CHANGE = 'MEMBER_STATUS_CHANGE', // istifa / ihraç / pasif

  // Aidat & Mali İşler
  DUES_PLAN_MANAGE = 'DUES_PLAN_MANAGE',
  DUES_PAYMENT_ADD = 'DUES_PAYMENT_ADD',
  DUES_REPORT_VIEW = 'DUES_REPORT_VIEW',
  DUES_DEBT_LIST_VIEW = 'DUES_DEBT_LIST_VIEW',
  DUES_EXPORT = 'DUES_EXPORT',

  // Şube / İl / İlçe Yönetimi
  REGION_LIST = 'REGION_LIST',
  BRANCH_MANAGE = 'BRANCH_MANAGE',
  BRANCH_ASSIGN_PRESIDENT = 'BRANCH_ASSIGN_PRESIDENT',

  // İş Yeri Yönetimi
  WORKPLACE_LIST = 'WORKPLACE_LIST',
  WORKPLACE_MANAGE = 'WORKPLACE_MANAGE',
  WORKPLACE_ASSIGN_REP = 'WORKPLACE_ASSIGN_REP',
  WORKPLACE_MEMBERS_VIEW = 'WORKPLACE_MEMBERS_VIEW',

  // Bayilik Sistemi
  DEALER_LIST = 'DEALER_LIST',
  DEALER_CREATE = 'DEALER_CREATE',
  DEALER_APPROVE_APPLICATION = 'DEALER_APPROVE_APPLICATION',
  DEALER_UPDATE = 'DEALER_UPDATE',
  DEALER_PERFORMANCE_VIEW = 'DEALER_PERFORMANCE_VIEW',

  // İçerik Yönetimi
  CONTENT_MANAGE = 'CONTENT_MANAGE', // haber/duyuru/etkinlik CRUD
  CONTENT_PUBLISH = 'CONTENT_PUBLISH',

  // Evrak & Doküman
  DOCUMENT_TEMPLATE_MANAGE = 'DOCUMENT_TEMPLATE_MANAGE',
  DOCUMENT_MEMBER_HISTORY_VIEW = 'DOCUMENT_MEMBER_HISTORY_VIEW',
  DOCUMENT_GENERATE_PDF = 'DOCUMENT_GENERATE_PDF',

  // Raporlar & Dashboard
  REPORT_GLOBAL_VIEW = 'REPORT_GLOBAL_VIEW',
  REPORT_REGION_VIEW = 'REPORT_REGION_VIEW',
  REPORT_MEMBER_STATUS_VIEW = 'REPORT_MEMBER_STATUS_VIEW',
  REPORT_DUES_VIEW = 'REPORT_DUES_VIEW',

  // Bildirim & İletişim
  NOTIFY_ALL_MEMBERS = 'NOTIFY_ALL_MEMBERS',
  NOTIFY_REGION = 'NOTIFY_REGION',
  NOTIFY_OWN_SCOPE = 'NOTIFY_OWN_SCOPE',

  // Sistem Ayarları & Loglar
  SYSTEM_SETTINGS_VIEW = 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_MANAGE = 'SYSTEM_SETTINGS_MANAGE',
  LOG_VIEW_ALL = 'LOG_VIEW_ALL',
  LOG_VIEW_OWN_SCOPE = 'LOG_VIEW_OWN_SCOPE',
}
