export enum Permission {
  // Kullanıcı Yönetimi
  USER_LIST = 'USER_LIST',
  USER_VIEW = 'USER_VIEW',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_SOFT_DELETE = 'USER_SOFT_DELETE',
  USER_ASSIGN_ROLE = 'USER_ASSIGN_ROLE',

  // Rol & Yetki Yönetimi
  ROLE_LIST = 'ROLE_LIST',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_MANAGE_PERMISSIONS = 'ROLE_MANAGE_PERMISSIONS',

  // Üye Yönetimi
  MEMBER_LIST = 'MEMBER_LIST',
  MEMBER_VIEW = 'MEMBER_VIEW',
  MEMBER_CREATE_APPLICATION = 'MEMBER_CREATE_APPLICATION',
  MEMBER_APPROVE = 'MEMBER_APPROVE',
  MEMBER_REJECT = 'MEMBER_REJECT',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_STATUS_CHANGE = 'MEMBER_STATUS_CHANGE', // istifa / ihraç / pasif
  MEMBER_LIST_BY_PROVINCE = 'MEMBER_LIST_BY_PROVINCE', // Belirli bir ildeki üyeleri görüntüleme (UserScope'daki provinceId'ye göre)


  // Şube / İl / İlçe Yönetimi
  REGION_LIST = 'REGION_LIST',
  BRANCH_MANAGE = 'BRANCH_MANAGE',
  BRANCH_ASSIGN_PRESIDENT = 'BRANCH_ASSIGN_PRESIDENT',

  // İçerik Yönetimi
  CONTENT_MANAGE = 'CONTENT_MANAGE', // haber/duyuru/etkinlik CRUD
  CONTENT_PUBLISH = 'CONTENT_PUBLISH',

  // Evrak & Doküman
  DOCUMENT_TEMPLATE_MANAGE = 'DOCUMENT_TEMPLATE_MANAGE',
  DOCUMENT_MEMBER_HISTORY_VIEW = 'DOCUMENT_MEMBER_HISTORY_VIEW',
  DOCUMENT_GENERATE_PDF = 'DOCUMENT_GENERATE_PDF',

  // Raporlar & Dashboard
  REPORT_GLOBAL_VIEW = 'REPORT_GLOBAL_VIEW',
  REPORT_REGION_VIEW = 'REPORT_REGION_VIEW',
  REPORT_MEMBER_STATUS_VIEW = 'REPORT_MEMBER_STATUS_VIEW',
  REPORT_DUES_VIEW = 'REPORT_DUES_VIEW',

  // Bildirim & İletişim
  NOTIFY_ALL_MEMBERS = 'NOTIFY_ALL_MEMBERS',
  NOTIFY_REGION = 'NOTIFY_REGION',
  NOTIFY_OWN_SCOPE = 'NOTIFY_OWN_SCOPE',

  // Sistem Ayarları & Loglar
  SYSTEM_SETTINGS_VIEW = 'SYSTEM_SETTINGS_VIEW',
  SYSTEM_SETTINGS_MANAGE = 'SYSTEM_SETTINGS_MANAGE',
  LOG_VIEW_ALL = 'LOG_VIEW_ALL',
  LOG_VIEW_OWN_SCOPE = 'LOG_VIEW_OWN_SCOPE',

  // Kurumlar (Institutions)
  INSTITUTION_LIST = 'INSTITUTION_LIST',
  INSTITUTION_VIEW = 'INSTITUTION_VIEW',
  INSTITUTION_CREATE = 'INSTITUTION_CREATE',
  INSTITUTION_UPDATE = 'INSTITUTION_UPDATE',
  INSTITUTION_APPROVE = 'INSTITUTION_APPROVE',

  // Muhasebe
  ACCOUNTING_VIEW = 'ACCOUNTING_VIEW',
  ACCOUNTING_EXPORT = 'ACCOUNTING_EXPORT',
  TEVKIFAT_FILE_UPLOAD = 'TEVKIFAT_FILE_UPLOAD',
  TEVKIFAT_FILE_APPROVE = 'TEVKIFAT_FILE_APPROVE',

  // Üye Ödemeleri
  MEMBER_PAYMENT_ADD = 'MEMBER_PAYMENT_ADD', // Ödeme girişi (Muhasebe)
  MEMBER_PAYMENT_APPROVE = 'MEMBER_PAYMENT_APPROVE', // Ödeme onaylama (Admin)
  MEMBER_PAYMENT_LIST = 'MEMBER_PAYMENT_LIST', // Ödeme listesi görüntüleme
  MEMBER_PAYMENT_VIEW = 'MEMBER_PAYMENT_VIEW', // Ödeme detay görüntüleme

  // Onay Süreçleri
  APPROVAL_VIEW = 'APPROVAL_VIEW',
  APPROVAL_APPROVE = 'APPROVAL_APPROVE',
  APPROVAL_REJECT = 'APPROVAL_REJECT',
}
